a=input('Ho ten: ')
b=int(input('So ngay cong:'))
c=int(input('Don gia ngay cong:'))
d=float(input('He so phu cap:'))
e=int(input('Tam ung:'))
L=float(c*b*d)
TL=float(L-e)
print('Nhan vien',a,',Co tien Luong=',round(L,1),',Tam ung=',e,'va Thuc linh=',round(TL,1))
